name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          sudo apt-get install -y gh

      - name: Check for Changes in Project A
        id: project_a_changes
        run: |
          git fetch origin main
          if git diff --name-only origin/main -- 'project-a/*' | grep -q '.'; then
            echo "project-a changed"
            echo "changed=true" >> $GITHUB_ENV
            echo "service_name=project-a" >> $GITHUB_ENV
          else
            echo "changed=false" >> $GITHUB_ENV
          fi
          
      - name: Dispatch Event for Project A
        if: env.changed == 'true'
        run: |
          gh api repos/${{ github.repository }}/dispatches \
            -F event_type=service_updated \
            -F client_payload='{"service_name": "project-a"}'

      - name: Check for Changes in Project B
        id: project_b_changes
        run: |
          if git diff --name-only origin/main -- 'project-b/*' | grep -q '.'; then
            echo "project-b changed"
            echo "changed=true" >> $GITHUB_ENV
            echo "service_name=project-b" >> $GITHUB_ENV
          else
            echo "changed=false" >> $GITHUB_ENV
          fi
          
      - name: Dispatch Event for Project B
        if: env.changed == 'true'
        run: |
          gh api repos/${{ github.repository }}/dispatches \
            -F event_type=service_updated \
            -F client_payload='{"service_name": "project-b"}'
