name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
      MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Modal
        run: |
          python -m pip install --upgrade pip
          pip install modal

      - name: Check for Changes in Project A
        id: project_a_changes
        run: |
          git fetch origin main
          git diff --name-only origin/main -- 'project-a/*' > project_a_changes.txt
        continue-on-error: true

      - name: Check for Changes in Project B
        id: project_b_changes
        run: |
          git fetch origin main
          git diff --name-only origin/main -- 'project-b/*' > project_b_changes.txt
        continue-on-error: true

      - name: Deploy Project A Endpoint
        if: ${{ steps.project_a_changes.outputs.changed != '' }}
        run: |
          echo "Changes detected in project-a. Deploying endpoint-a.py..."
          modal deploy --env=sandbox project-a/endpoint-a.py

      - name: Deploy Project B Endpoint
        if: ${{ steps.project_b_changes.outputs.changed != '' }}
        run: |
          echo "Changes detected in project-b. Deploying endpoint-b.py..."
          modal deploy --env=sandbox project-b/endpoint-b.py
